# Generated by Django 5.2.3 on 2025-06-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='malariaimage',
            name='noteMedical',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='malariaimage',
            name='paatient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
